Repository coreos/afterburn, pull requests merged in 2019-10, with the labels that each got.

#283 providers: add Alibaba Cloud (aliyun)
  Cargo.lock
  Cargo.toml
  README.md
  src/metadata.rs
  src/providers/aliyun/mock_tests.rs
  src/providers/aliyun/mod.rs
  src/providers/mod.rs
Labels: kind/enhancement, platform/aliyun

#286 tests/gcp: avoid flake
  src/providers/gcp/mock_tests.rs
Labels: area/testing, kind/cleanup, platform/gcp

#287 systemd: allow sshkeys service on aliyun
  systemd/afterburn-sshkeys@.service.in
Labels: area/usability, kind/bug, platform/aliyun

#278 providers: fetch instance types for all providers
  README.md
  docs/container-linux-legacy.md
  src/providers/aws/mock_tests.rs
  src/providers/aws/mod.rs
  src/providers/azure/mock_tests.rs
  src/providers/azure/mod.rs
  src/providers/gcp/mock_tests.rs
  src/providers/gcp/mod.rs
  src/providers/openstack/network.rs
  src/providers/packet/mock_tests.rs
  src/providers/packet/mod.rs
Labels: area/usability, kind/enhancement

#288 Release 4.2.0
  Cargo.lock
  Cargo.toml
Labels: kind/release

#296 providers: rework to speed up negative tests
  src/providers/azure/mock_tests.rs
  src/providers/azure/mod.rs
  src/providers/packet/mock_tests.rs
  src/providers/packet/mod.rs
Labels: area/testing, kind/enhancement

#297 cloudstack-configdrive: cleanup mounting and umounting logic
  src/providers/cloudstack/configdrive.rs
  src/retry/mod.rs
  src/util/mod.rs
  src/util/mount.rs
Labels: area/stability, kind/cleanup, platform/cloudstack

#298 github: add release-checklist template
  .github/ISSUE_TEMPLATE/release-checklist.md
  docs/development.md
  docs/release-guide.md
Labels: area/developer tooling, kind/enhancement
