Repository coreos/afterburn, pull requests merged in 2020-07, with the labels that each got.

#450 providers: mark vagrant-virtualbox as legacy
  README.md
  docs/usage/attributes.md
  src/metadata.rs
  src/providers/mod.rs
Labels: kind/cleanup, platform/vagrant-virtualbox

#454 providers/azure: do not fail on keyless instances
  src/providers/azure/mock_tests.rs
  src/providers/azure/mod.rs
Labels: area/usability, kind/bug, platform/azure

#457 Release 4.4.2
  Cargo.lock
  Cargo.toml
Labels: kind/release

#451 platform: add support for vultr
  README.md
  docs/usage/attributes.md
  docs/usage/legacy-attributes.md
  src/metadata.rs
  src/providers/mod.rs
  src/providers/vultr/mock_tests.rs
  src/providers/vultr/mod.rs
Labels: kind/enhancement, platform/vultr

#460 systemd: activate relevant services on Vultr
  dracut/30afterburn/afterburn-hostname.service
  systemd/afterburn-sshkeys@.service.in
Labels: kind/cleanup, platform/vultr
