Repository coreos/afterburn, pull requests merged in 2020-11, with the labels that each got.

#515 ci: move Travis jobs to GitHub actions
  .github/workflows/rust.yml
  .travis.yml
Labels: area/testing, kind/cleanup

#487 dracut: run hostname service on aliyun
  dracut/30afterburn/afterburn-hostname.service
Labels: area/usability, kind/bug, platform/aliyun

#516 dracut/hostname: run service on ibmcloud
  dracut/30afterburn/afterburn-hostname.service
Labels: area/usability, kind/enhancement, platform/ibmcloud

#518 cmdline: Just use std::fs::read_to_string()
  src/util/cmdline.rs
Labels: kind/cleanup

#513 providers/*stack: allow 404 returns on *stack network provider
  src/providers/cloudstack/mock_tests.rs
  src/providers/cloudstack/mod.rs
  src/providers/cloudstack/network.rs
  src/providers/openstack/mock_tests.rs
  src/providers/openstack/mod.rs
  src/providers/openstack/network.rs
Labels: kind/bug, platform/cloudstack, platform/openstack

#520 workflows/rust: update linting toolchain to latest stable
  .github/workflows/rust.yml
  src/cli/exp.rs
  src/providers/azure/mod.rs
Labels: area/developer tooling, kind/cleanup
