Repository coreos/afterburn, pull requests merged in 2020-09, with the labels that each got.

#484 ci: bump linting toolchain on Travis
  .travis.yml
Labels: area/testing, kind/enhancement

#486 Release 4.5.1
  Cargo.lock
  Cargo.toml
Labels: kind/release

#491 docs: clarify afterburn.service enablement
  docs/usage/attributes.md
  systemd/afterburn.service
Labels: kind/documentation

#493 sshkeys: activate service on OpenStack
  systemd/afterburn-sshkeys@.service.in
Labels: kind/enhancement, platform/openstack
